### ISSUE TITLE
[Suggestion] Remove unsuported enchantments from GUI + Toggle enchantments from GUI

### ISSUE THREAD

**Issue by heide-oficial** [Akinesis/better-enchanting#27]
I noticed that for a unsuported enchantment we get to need to use a "barrier" to level up. As barrier aren't obtainable in survival mode, I think it would better to just hide these enchantments (as it adds unnecessary elements to the enchanting table GUI). 

Along the same lines, I think it would be cool to toggle every enchantment from the GUI (using a config menu/file), so this way other people can just toggle enchantments that aren't supported or they don't like.

**Comment by Akinesis** [comment]
The barrier are here to clearly notify that somthing is wrong in the configuration of the mod.
It's an intentional feature and will stay like this. To resolve missing entries, see [Modifing ingredients list and adding support to moded enchantments.](https://github.com/Akinesis/better-enchanting/wiki/Modifing-ingredients-list-and-adding-support-to-moded-enchantments.).
As for removing unwanted enchantments, this is not the goal of that mod and never will be. This owever is feasable by the mean of Datapack or mods preaty easily. As my mod only propose in the nechanting table Enchantment with the tag of `treasure` and `in_enchanting_table`, any enchantment not is these two tags will not show in the enchanting table.

**Comment by antieksi** [comment]
Sorry for bringing this back, but there is a point that should be made: some vanilla enchantments aren't intended to be obtained through Enchanting table, such as Mending, Frost Walker, Soul Speed, Wind Burst and Swift Sneak. I'd propose a config option to manually exclude groups by tags, such as disallowing all `#minecraft:treasure` enchants or even making some mod enchantments unaccessible.

It is already kind of possible; in my own config I've just removed all items from several entries, and though it doesn't hide them from Enchanting table, it makes them impossible to get through it.

**Comment by Akinesis** [comment]
Ho yeah, that's a good point. As Essences can be found in treasure ...
I'll add this in my list of thing to do in the upcoming "Config Update".

Thank you for pointing it out.

**Comment by Akinesis** [comment]
1.0 version of the mod , th "Configuration Update" is out.
You can diasble from the enchanting table any enchantment you whant via a new config file.
Most value used on the calculation of Xp and Itmes cost are also now configurable.
Enjoy :)
