### ISSUE TITLE
Mending & Other Enchants Questions

### ISSUE THREAD

**Issue by CobraNaja** [Akinesis/better-enchanting#32]
Hello there,

Got a couple of questions as we're trying to make your mod work on our server.

First, I saw the Essence of Mending recipe, but when I place a pickaxe or other item in the enchanting table, it doesn't even show me the possibility of mending (with the missing Enchantment item). Am I missing something to making it show up?

Other than that, we're using the mods from the RPG series (mages, paladins, rogues, etc etc), and while we can enchant bows, maces, and most weapons. I don't have options for staffs or wands. Is it possible to get that working too?

Thirdly, there are multiple enchantments that require "1 Barrier" but it doesn't say how to craft that.  Sometimes it's on enchants like Fertility on a helmet, I can just imagine that it's not supposed to be there. But for example, I have Spell Breaking III on my diamond helmet. But to upgrade it to Spell Breaking IV or V, it says 1 Barrier.

Thanks for your help!
CobraNaja

**Comment by CobraNaja** [comment]
Fixed the mending part, and the rpg series part :)

Just need clarification on the 1 Barrier, when possible :)
Thanks!

**Comment by antieksi** [comment]
Barrier basically means that there are no means to get that enchantment.

**Comment by CobraNaja** [comment]
Would I be able to edit that in the enchantment_ingredients.json file?
If I find the correct mods and names*
And if yes, I do have 2 quick questions:

1) Imagine there's an enchantment called Penetrating Strike from the mod BetterArcheology, with no tier levels. In theory, I should be able to add that in the json file? (if I name it like you did for minecraft or nova_structures spells) ? (and add enchantment ingredients requirements below it)

2) How do you edit the number of enchantment items needed for a tier? For example, I saw some enchantment tier needed 5 Flints, but in the json file, it only mentions the flint namespace, not the amount.


Sorry if I'm bothering you with these questions.

**Comment by Akinesis** [comment]
Hello, barriers meand in deed that some enchantments are detected by the game but have no configuration entries.
See : [Wiki - Adding support to moded enchantments](https://github.com/Akinesis/better-enchanting/wiki/Modifing-ingredients-list-and-adding-support-to-moded-enchantments.) for more info on that :)
This should answer your first question.
As for the second one, as of right now, the number of items needed as ingredients is a bit of a "magic number" wich is calculated based on the enchant rarity and level.
I have plan to make it more configurable but haven't stared the dev on this yet.

I hope this was helpfull.

**Comment by CobraNaja** [comment]
Wow, super useful! :D 
+ super quick response. Thank you! :)

I just need to figure out the standard names from the other mods that bring enchantments then...
Thanks again!!!

**Comment by CobraNaja** [comment]
Last question: there are some essences recipes from the jar that we don't use (essence of mining, essence of smelting, for example).
I'm guessing if we add the other mods that are compatible with this one and that have corresponding enchantments, the json file would automatically update?

Thanks again!

**Comment by Akinesis** [comment]
Yup exactly. These essence should not be visible outside the creative tab anyway.
But yeah, as theses are compatibility essences for datapacks, it's harder to load them dinamicly and i just didn't bother to do so :D

**Comment by CobraNaja** [comment]
Yea, we have JEI, I think that's what's showing all the essence recipes in our menu.
Ok, so plan is we'll install Neo Enchant+, that should use the full capabilities of your mod. And I figured the name of some of the enchants from BetterArcheology, I just need to figure out for Spell Engine/Power mods which is the bigger chunk, for mages...

Anyhow, you've been VERY helpful :D
Thanks again!

**Comment by CobraNaja** [comment]
Profiting from the ticket still open... and hello again :D

Frost walking the vanilla enchantment applies to Gold boots, but isn't an option on Diamond boots. Bug?

**Comment by Akinesis** [comment]
Hellon i've keep the issue open in case you'd have more questions, don't worry.
Enchantment avalaible on the enchanting table mimic the vanillia way as for what enchant are visible depending on the number of bookshelves around the enchanting table, but also the enchentability value of the object.
As gold have a highier enchantability than diamond, it may better enchants appearing for gold items is normal.

BUT, If you have at least 15 bookshelvs around your enchanting table and your are of a decently hight level (let's say, more than 15) all enchantments should be present for equipments of Gold tiers or higier (I.E. : Diamons, Netherite and any moded items of the same level).

I've tested this on my personal server with no issue, but please do keep me in touch with this issue here :D

**Comment by CobraNaja** [comment]
So despite appearances, I'm still a noob at minecraft x)

But, I have enchantment power 26 around the enchantment table and i'm level 36.
I did check online that diamond armor has less enchantments than gold items like you mentioned, but I don't know why some of the enchantments don't seem to popup on my items as choices...

On another note, if you ever want to adapt your mod for Ender Zoology, Better Archeology, More Spell Attributes, Spell Power Attributes, Extra RPG Attributes, Spell Power & Spell Engine mods, I may be able to help lol XD
I've managed to adapt your json file with most of their enchantments (still got issues with 4 of them, work in progress) :D

**Comment by Akinesis** [comment]
Huuummm, yeah weird. All applicable enchant should be visible if you have enought libraries aroud your enchanting tables ...

As for compat, since the last update, the mod is fully compatible with the "Spell engine suite", you might need to delete your config file for it to reload with the new additions ...
As for the others mods, yeah the list could be endless. But in time more and more mods will be fully interated.

Hope this have helped.
